### ISSUE TITLE
When I try to import the gym_pull, it said no module named  'gym.configuration'

### ISSUE THREAD

**Issue by Flyme-jin** [ppaquette/gym_pull#11]
Traceback (most recent call last):
  File "/Users/baohejin/Documents/mario.py", line 2, in <module>
    import gym_pull
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gym_pull/__init__.py", line 6, in <module>
    from gym.configuration import logger_setup, undo_logger_setup
ModuleNotFoundError: No module named 'gym.configuration'

**Comment by tmcarn** [comment]
I have this same issue, did you find a solution?
