### ISSUE TITLE
Error on importing gym_pull

### ISSUE THREAD

**Issue by shashank879** [ppaquette/gym_pull#5]
I installed this using: 'pip3 install gym-pull', I assumed it is available on python3
Now on trying to import it using: 'import gym_pull', it gives an error.

```
In [1]: import gym_pull

Usage:   
  pip list [options]

no such option: --format
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-1e180c64cd42> in <module>()
----> 1 import gym_pull

/Users/Shashank/Library/Python/3.5/lib/python/site-packages/gym_pull/__init__.py in <module>()
     50 logger.setLevel(logging.INFO)
     51 from gym_pull.envs import list
---> 52 from gym_pull.package import pull
     53 
     54 __all__ = ["Env", "Space", "Wrapper", "list", "make", "pull", "spec", "upload"]

/Users/Shashank/Library/Python/3.5/lib/python/site-packages/gym_pull/package/__init__.py in <module>()
      2 
      3 # Loading user environments
----> 4 load_user_envs()

/Users/Shashank/Library/Python/3.5/lib/python/site-packages/gym_pull/package/manager.py in load_user_envs(self)
     31     def load_user_envs(self):
     32         """ Loads downloaded user envs from filesystem cache on `import gym` """
---> 33         installed_packages = self._list_packages()
     34 
     35         # Tagging core envs

/Users/Shashank/Library/Python/3.5/lib/python/site-packages/gym_pull/package/manager.py in _list_packages(self)
    184         self._run_cmd('{} list --format=legacy --log {} > {}'.format(pip_exec, temp_file, os.devnull))
    185 
--> 186         with open(temp_file) as f:
    187             for line in f:
    188                 match = package_re.search(line)

FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/1d/5st6x64j7lj7xy2c6qx_dwlm0000gn/T/tmponk3682q/pip_list.txt'
```

**Comment by absolutelyNoWarranty** [comment]
@shashank879 Are you using gym_pull in a virtualenv? See my pr #6

**Comment by shubhoghosal** [comment]
import gym_pull raises the following error:
/bin/sh: pip3: command not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shubhoghosal/anaconda3/lib/python3.6/site-packages/gym_pull/__init__.py", line 52, in <module>
    from gym_pull.package import pull
  File "/Users/shubhoghosal/anaconda3/lib/python3.6/site-packages/gym_pull/package/__init__.py", line 4, in <module>
    load_user_envs()
  File "/Users/shubhoghosal/anaconda3/lib/python3.6/site-packages/gym_pull/package/manager.py", line 33, in load_user_envs
    installed_packages = self._list_packages()
  File "/Users/shubhoghosal/anaconda3/lib/python3.6/site-packages/gym_pull/package/manager.py", line 186, in _list_packages
    with open(temp_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/01/sk2yzmcd4cxby3nxt6z1c3jw0000gn/T/tmpvi0b4dug/pip_list.txt'

**Comment by shashank879** [comment]
@absolutelyNoWarranty no

**Comment by schneblizoltan** [comment]
Same problem here. @shashank879 nothing changed after modifying the code

**Comment by absolutelyNoWarranty** [comment]
@schneblizoltan @shashank879 
Try upgrading the `pip` you used to install `gym-pull` with `pip install --upgrade pip`. `gym-pull` is running a hard-coded shell command (`pip list --format legacy`) and really old versions of pip didn't have `--format`.
