### ISSUE TITLE
Error on importing gym-pull (anaconda3)

### ISSUE THREAD

**Issue by makerjackie** [ppaquette/gym_pull#7]
Usage:   
  pip list [options]

no such option: --format
Traceback (most recent call last):
  File "super-mario.py", line 2, in <module>
    import gym_pull
  File "/home/jackie/anaconda3/lib/python3.6/site-packages/gym_pull/__init__.py", line 52, in <module>
    from gym_pull.package import pull
  File "/home/jackie/anaconda3/lib/python3.6/site-packages/gym_pull/package/__init__.py", line 4, in <module>
    load_user_envs()
  File "/home/jackie/anaconda3/lib/python3.6/site-packages/gym_pull/package/manager.py", line 33, in load_user_envs
    installed_packages = self._list_packages()
  File "/home/jackie/anaconda3/lib/python3.6/site-packages/gym_pull/package/manager.py", line 186, in _list_packages
    with open(temp_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp8mob_ina/pip_list.txt'

**Comment by makerjackie** [comment]
Solve, sorry I miss the pull request
https://github.com/ppaquette/gym-pull/pull/6/commits/39b09b9945442f620ff3ca6db581e42a2b4eca6a
