### ISSUE TITLE
pip list problem on gym pull

### ISSUE THREAD

**Issue by mcbrs1a** [ppaquette/gym_pull#9]
On a different build i get:

 import gym_pull

Usage:   
  pip list [options]

no such option: --format
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/petic/.local/lib/python2.7/site-packages/gym_pull/__init__.py", line 52, in <module>
    from gym_pull.package import pull
  File "/home/petic/.local/lib/python2.7/site-packages/gym_pull/package/__init__.py", line 4, in <module>
    load_user_envs()
  File "/home/petic/.local/lib/python2.7/site-packages/gym_pull/package/manager.py", line 33, in load_user_envs
    installed_packages = self._list_packages()
  File "/home/petic/.local/lib/python2.7/site-packages/gym_pull/package/manager.py", line 186, in _list_packages
    with open(temp_file) as f:
IOError: [Errno 2] No such file or directory: '/tmp/tmp5lAGz7/pip_list.txt'

**Comment by absolutelyNoWarranty** [comment]
Upgrade `pip` (`pip install --upgrade pip`) or try PR #3
